name: Check for Complete Package Build

on: 
  pull_request: 
    branches:
    - '**'
  push: 
    branches:
    - '**'
  workflow_dispatch: 
  
jobs: 
  build: 
    name: Building the application's frontend package.
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setting up the application's node modules
        uses: actions/setup-node@v5
        with:
          node-version: '24.x'
          cache: 'yarn'

      - name: Enabling corepack and setting yarn to the most stable version
        run: |
          corepack enable
          yarn set version stable

      - name: Installing dependencies using yarn
        run: yarn install

      - name: Adding sv-router's generated routes file
        run: yarn run generate-routes

      - name: Checking types and building the window's application
        run: yarn run build